const data = {
  products: [
    {
      _id: '1',
      name: 'HENDERSOn',
      category: 'classic suit',
      image: '/images/s1.jpg',
      price: 1230,
      brand: 'HENDERSON',
      rating: 3.6,
      numReviews: 10,
      description:
        'Lorem ipsum dolor sit amet, ex usu deserunt inciderint, quis accusam accusamus ea nec. Duo placerat mandamus ne, per eu tollit salutatus vituperata. Vix partem quaestio assueverit an.',
      tags: ['suit', 'classic suit'],
      countInStoke: 2,
    },
    {
      _id: '2',
      name: 'T-Shirt',
      category: 'Shirts',
      image: '/images/s1.jpg',
      price: 100,
      brand: 'Reda',
      rating: 4.5,
      numReviews: 10,
      description:
        'Lorem ipsum dolor sit amet, ex usu deserunt inciderint, quis accusam accusamus ea nec. Duo placerat mandamus ne, per eu tollit salutatus vituperata. Vix partem quaestio assueverit an.',
      tags: ['suit', 'classic suit'],
      countInStoke: 0,
    },
    {
      _id: '3',
      name: 'Slim Shirt',
      category: 'Shirts',
      image: '/images/s1.jpg',
      price: 150,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description:
        'Lorem ipsum dolor sit amet, ex usu deserunt inciderint, quis accusam accusamus ea nec. Duo placerat mandamus ne, per eu tollit salutatus vituperata. Vix partem quaestio assueverit an.',
      tags: ['suit', 'classic suit'],
      countInStoke: 4,
    },
    {
      _id: '4',
      name: 'Shirts',
      category: 'Shirts',
      image: '/images/s1.jpg',
      price: 180,
      brand: 'Adidas',
      rating: 5,
      numReviews: 10,
      description:
        'Lorem ipsum dolor sit amet, ex usu deserunt inciderint, quis accusam accusamus ea nec. Duo placerat mandamus ne, per eu tollit salutatus vituperata. Vix partem quaestio assueverit an.',
      tags: ['suit', 'classic suit'],
      countInStoke: 2,
    },
    {
      _id: '5',
      name: 'T-Shirts',
      category: 'classic suit',
      image: '/images/s1.jpg',
      price: 220,
      brand: 'Lacoste',
      rating: 4.5,
      numReviews: 10,
      description:
        'Lorem ipsum dolor sit amet, ex usu deserunt inciderint, quis accusam accusamus ea nec. Duo placerat mandamus ne, per eu tollit salutatus vituperata. Vix partem quaestio assueverit an.',
      tags: ['suit', 'classic suit'],
      countInStoke: 5,
    },
    {
      _id: '6',
      name: 'T-Shirts',
      category: 'classic suit',
      image: '/images/s1.jpg',
      price: 220,
      brand: 'Lacoste',
      rating: 4.5,
      numReviews: 10,
      description:
        'Lorem ipsum dolor sit amet, ex usu deserunt inciderint, quis accusam accusamus ea nec. Duo placerat mandamus ne, per eu tollit salutatus vituperata. Vix partem quaestio assueverit an.',
      tags: ['suit', 'classic suit'],
      countInStoke: 2,
    },
    {
      _id: '7',
      name: 'T-Shirts',
      category: 'classic suit',
      image: '/images/s1.jpg',
      price: 220,
      brand: 'Lacoste',
      rating: 4.5,
      numReviews: 10,
      description:
        'Lorem ipsum dolor sit amet, ex usu deserunt inciderint, quis accusam accusamus ea nec. Duo placerat mandamus ne, per eu tollit salutatus vituperata. Vix partem quaestio assueverit an.',
      tags: ['suit', 'classic suit'],
      countInStoke: 1,
    },
    {
      _id: '8',
      name: 'Slim Shirt',
      category: 'Shirts',
      image: '/images/s1.jpg',
      price: 150,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description:
        'Lorem ipsum dolor sit amet, ex usu deserunt inciderint, quis accusam accusamus ea nec. Duo placerat mandamus ne, per eu tollit salutatus vituperata. Vix partem quaestio assueverit an.',
      tags: ['suit', 'classic suit'],
      countInStoke: 4,
    },
  ],
};

export default data;
