export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCES = 'ORDER_CREATE_SUCCES';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCES = 'ORDER_DETAILS_SUCCES';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';
