const data = {
  products:[
    {
      _id: '1',
      name: "HENDERSON",
      category: "classic suit",
      image: '/images/s1.jpg',
      price: 120,
      brand:'HENDERSON',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
    {
      _id: '2',
      name: "T-Shirt",
      category: "Shirts",
      image: '/images/s1.jpg',
      price: 100,
      brand:'Reda',
      rating: 4.5,
      numReviews: 10,
      description: 'Medium quality product',
    },
    {
      _id: '3',
      name: "Slim Shirt",
      category: "Shirts",
      image: '/images/s1.jpg',
      price: 150,
      brand:'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'Low quality product',
    },
    {
      _id: '4',
      name: "Shirts",
      category: "Shirts",
      image: '/images/s1.jpg',
      price: 180,
      brand:'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'Medium quality product',
    },
    {
      _id: '5',
      name: "T-Shirts",
      category: "classic suit",
      image: '/images/s1.jpg',
      price: 220,
      brand:'Lacoste',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality product',
    },
  ]
}

export default data;